version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: "Update NPM"
          command: 'sudo npm install -g npm@latest'
      - run:
          name: "Install Client Dependencies"
          command: cd junkdog-client && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "junkdog-client/package.json" }}
          paths:
            - junkdog-client/node_modules
      - run:
          name: "Install Server Dependencies"
          command: cd junkdog-server && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "junkdog-server/package.json" }}
          paths:
            - junkdog-server/node_modules
      - run:
          name: "Run Client Tests"
          command: cd junkdog-client && npm run test --ci --runInBand --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/jest/results.xml"
      - run:
          name: "Flow Client Code Coverage"
          command: cd junkdog-client && npm run flow:ci
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage.xml
          prefix: coverage
      - store_test_results:
          path: reports
workflows:
  version: 2
  build:
    jobs:
      - build
