version: 2
jobs:
  build:
    working_directory: ../
    docker:
      - image: circleci/node
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: cd junkdog-client && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./junkdog-client/node_modules
      - run:
          name: install-server-npm
          command: cd junkdog-server && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./junkdog-server/node_modules
      - run:
          name: "Run Tests"
          command: cd junkdog-cient && npm run test --ci --runInBand --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/jest/results.xml"
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: reports
